version: '3'

services:

  server:
    container_name: plotter
    build: .
    ports:
      - 8080:8080
#    network_mode: host
    environment:
      - PORT=8080
    working_dir:
      /PlotterServer
    volumes:
      - ./:/PlotterServer
    command: tail -f /dev/null
