version: '3'

services:

  server:
    container_name: plotter-server
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    working_dir:
      /work
    volumes:
      - ./work:/work
      - ./tools:/tools
      - ./server:/plotter
    command: tail -f /dev/null
