version: '3'

services:

  server:
    container_name: plotter-server
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    volumes:
      - ./work:/work
      - ./server:/plotter
    command: tail -f /dev/null

  client:
    container_name: plotter-client
    build: .
    environment:
      - PORT=8080
    depends_on:
      - server
