version: '3'

services:

  plt:
    container_name: plt
    build: .
    ports:
      - 8080:8080
    environment:
      - PLT_HOST=localhost
      - PLT_PORT=8080
    volumes:
      - ./:/plt
    working_dir: /plt
    command: tail -f /dev/null
